services:
  - type: web
    name: whatsapp-web-clone
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /
    autoDeploy: true
